const os=require('os');
console.log(os.platform());
console.log(os.totalmem());
console.log(os.freemem());
console.log(os.arch());
console.log(os.homedir());
console.log(os.version());
console.log(os.tmpdir());
console.log(os.userInfo());
console.log(os.networkInterfaces());